# Generated by Django 5.0.7 on 2024-08-16 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи в БД'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения записи в БД'),
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(blank=True, help_text='Введите номер версии', max_length=10, null=True, verbose_name='Номер версии')),
                ('version_name', models.CharField(blank=True, help_text='Введите название версии', max_length=100, null=True, verbose_name='Название версии')),
                ('is_version_active', models.BooleanField(default=False, help_text='Является ли версия активной?', verbose_name='Активная версия')),
                ('product', models.ForeignKey(blank=True, help_text='Выберите продукт', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='catalog.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Версия',
                'verbose_name_plural': 'Версии',
                'ordering': ['version_number', 'version_name'],
            },
        ),
    ]
