# Generated by Django 5.0.7 on 2024-08-21 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_created_at_alter_product_updated_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
